function propert(a)
    % scalar
    b = length(a)
    disp(b)
    b = isscalar(a)
    disp(b)
    b = isvector(a)
    disp(b)
    b = isrow(a)
    disp(b)
    b = iscolumn(a)
    disp(b)
    b = ismatrix(a)
    disp(b)
    b = numel(a)
    disp(b)
    b = ndims(a)
    disp(b)
    b = isempty(a)
    disp(b)
    % matrix
    a = rand(a)
    b = length(a)
     disp(b)
    b = isscalar(a)
     disp(b)
    b = isvector(a)
     disp(b)
    b = isrow(a)
    disp(b)
    b = iscolumn(a)
    disp(b)
    b = ismatrix(a)
    disp(b)
    b = numel(a)
    disp(b)
    b = ndims(a)
    disp(b)
    b = isempty(a)
    disp(b)
end