% Get test for value analysis and code gen. All the values below should have defined propagated values.
function get_range_expr(a)
    c = rand(2,2)
    b = c(:,:)
    disp(b)
    d = c(:)
    disp(d)
    e = c(1:end)
    disp(e)
    g = c(1:end,:)
    disp(g)
    h = c(:,:,1,1,1,a)
    disp(h)
    k = c(:,:,1,1,1,1)
    disp(k)
    l = c(:,ones(2,2))
    disp(l)
    o = c(ones(2,8))
    disp(o)
    c = rand(2,a)
    o = c(ones(2,8))
    disp(o)
end