/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import matwably.Main;
import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testSomeLibraryMethod() {
        String[] args = {"filename1 filename2 -o outputfile.wasm -a '[sss']'"};
        //Main.main(args);
        assertTrue("someLibraryMethod should return 'true'",true);
    }

    @Test
    public void run() {
    }

    @Test
    public void someLibraryMethod() {
    }
}

